"""Create relationship before books and authors

Revision ID: 019652926277
Revises: a4624a4f5b77
Create Date: 2025-11-20 06:38:54.701306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '019652926277'
down_revision: Union[str, Sequence[str], None] = 'a4624a4f5b77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column('books', sa.Column('author_id', sa.Integer(), nullable=False))

    op.create_foreign_key('books_author_id_fkey', 'books', 'authors', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('books_author_id_fkey', 'books', type_='foreignkey')

    op.drop_column('books', 'author_id')

    # ### end Alembic commands ###
