"""Append roles in users

Revision ID: 18ee15c57707
Revises: 4f2ba74d6e22
Create Date: 2025-11-24 16:34:04.788336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18ee15c57707'
down_revision: Union[str, Sequence[str], None] = '4f2ba74d6e22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_reader', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_author', sa.Boolean(), nullable=False))
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_admin')
    op.drop_column('users', 'is_author')
    op.drop_column('users', 'is_reader')
    # ### end Alembic commands ###
