"""Make autogenerated fields

Revision ID: a4624a4f5b77
Revises: e53e25b957e9
Create Date: 2025-11-19 14:07:15.283300

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4624a4f5b77'
down_revision: Union[str, Sequence[str], None] = 'e53e25b957e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    op.alter_column('authors', 'created_at', server_default=sa.text('NOW()'))
    op.alter_column('authors', 'updated_at', server_default=sa.text('NOW()'))
    op.alter_column('books', 'created_at', server_default=sa.text('NOW()'))
    op.alter_column('books', 'updated_at', server_default=sa.text('NOW()'))

def downgrade():
    op.alter_column('authors', 'created_at', server_default=None)
    op.alter_column('authors', 'updated_at', server_default=None)
    op.alter_column('books', 'created_at', server_default=None)
    op.alter_column('books', 'updated_at', server_default=None)